version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.8.2
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          name: Build Docker image
          create-repo: true
          path: ./docker
          repo: $CIRCLE_PROJECT_REPONAME-nginx
          tag: 'latest,$CIRCLE_SHA1'
          filters:
            branches:
              only:
                - master